# 14th June 2026

# EDA - Exploratory Data Analysis in Python

In [9]:
import pandas as pd

df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") 

df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:


df.drop_duplicates(inplace=True)
#df.drop_duplicates(subset=["area_type","availability","price" ],inplace=True) # You can give columns to match else it will match all columns

df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [11]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5328
total_sqft         0
bath              73
balcony          605
price              0
dtype: int64

In [12]:
df.dropna(inplace=True)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00
...,...,...,...,...,...,...,...,...,...
13308,Built-up Area,Ready To Move,Bannerghatta Road,3 BHK,Baanise,1527,3.0,1.0,142.00
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [13]:
df.isna().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [ ]:
import pandas as pd

df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") 

df.drop_duplicates(inplace=True)
df.dropna(axis = 1 , inplace=True) 
# now it will delete column -- even if one value in column is null 
# delete the whole column 

df

                  area_type   availability total_sqft   price
0      Super built-up  Area         19-Dec       1056   39.07
1                Plot  Area  Ready To Move       2600  120.00
2            Built-up  Area  Ready To Move       1440   62.00
3      Super built-up  Area  Ready To Move       1521   95.00
4      Super built-up  Area  Ready To Move       1200   51.00
...                     ...            ...        ...     ...
13314  Super built-up  Area  Ready To Move       1715  112.00
13315        Built-up  Area  Ready To Move       3453  231.00
13316  Super built-up  Area  Ready To Move       3600  400.00
13317        Built-up  Area  Ready To Move       1141   60.00
13318  Super built-up  Area         18-Jun       4689  488.00

[12791 rows x 4 columns]

In [25]:
import pandas as pd

df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") 

df.drop_duplicates(inplace=True)

condition = df.isna().sum()*100/len(df) <= 30 # which columns have less than 30 % null values

selected_cols = df.columns[condition]
selected_cols

lf = df[selected_cols]
lf.isna().sum()
lf.dropna(inplace=True)
lf.isna().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [29]:
import pandas as pd

df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") 

df.drop_duplicates(inplace=True)

condition = df.isna().sum()*100/len(df) <= 30 # which columns have less than 30 % null values

selected_cols = df.columns[condition]
selected_cols

df = df[selected_cols]
df.isna().sum()

df.describe()
df.info()

<class 'pandas.DataFrame'>
Index: 12791 entries, 0 to 13318
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12791 non-null  str
 1   availability  12791 non-null  str
 2   location      12790 non-null  str
 3   size          12775 non-null  str
 4   total_sqft    12791 non-null  str
 5   bath          12718 non-null  float64
 6   balcony       12186 non-null  float64
 7   price         12791 non-null  float64
dtypes: float64(3), str(5)
memory usage: 899.4 KB

In [42]:
import pandas as pd

df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") 
df.drop_duplicates(inplace=True)
condition = df.isna().sum()*100/len(df) <= 30 # which columns have less than 30 % null values
selected_cols = df.columns[condition]
df = df[selected_cols]
#df.describe()
#df.info()

df['total_sqft'] = pd.to_numeric(df['total_sqft'],errors="coerce")
df.isna().sum()
df['total_sqft'] = df['total_sqft'].fillna(df['total_sqft'].mean()) # we have filled na values with mean 
df.isna().sum()
df['bath'] = df['bath'].fillna(df['bath'].median()) # we have filled na values with mean 
df.isna().sum()
df['balcony'] = df['balcony'].fillna(df['balcony'].median()) # we have filled na values with mean 
df.isna().sum()
df['location'] = df['location'].fillna(df['location'].mode()[0]) # [0] because in case 2 value are hightest then take first one
df.isna().sum()
df['size'] = df['size'].fillna(df['size'].mode()[0]) # [0] because in case 2 value are hightest then take first one
df.isna().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [ ]:
import pandas as pd

## We are using mod where categorial data  liek string where we cannot find mean / median
## mean - where floating values are there
## mediun - where we cna not have floating values.. only whole value eg no. of rooms in house


df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\gaming_addiction.csv") 
df.isna().sum()
df['subscription_status'] = df['subscription_status'].fillna(df['subscription_status'].mode()[0]) # [0] because in case 2 value are hightest then take first one
df.isna().sum()
df['depression_indicator'] = df['depression_indicator'].fillna(df['depression_indicator'].mean()) # [0] because in case 2 value are hightest then take first one
df.isna().sum()
df['gpa_or_performance_score'] = df['gpa_or_performance_score'].fillna(df['gpa_or_performance_score'].mean()) # [0] because in case 2 value are hightest then take first one
df.isna().sum()
df['addiction_severity'] = df['addiction_severity'].fillna(df['addiction_severity'].mode()[0]) # [0] because in case 2 value are hightest then take first one
df.isna().sum()

user_id                        0
age                            0
gender                         0
country                        0
occupation                     0
income_level                   0
years_gaming                   0
preferred_genre                0
platform                       0
device_type                    0
rank_tier                      0
daily_playtime_hours           0
weekly_play_sessions           0
late_night_sessions_hours      0
weekend_playtime_hours         0
consecutive_hours_max          0
multiplayer_ratio              0
toxic_chat_reports             0
rage_quit_frequency            0
in_game_purchases              0
monthly_spending_usd           0
lootbox_openings               0
subscription_status            0
stress_score                   0
loneliness_score               0
dopamine_dependency_index      0
self_control_score             0
impulsiveness_score            0
anxiety_level                  0
depression_indicator           0
emotional_stability            0
sleep_hours                    0
exercise_frequency_per_week    0
caffeine_intake_cups_day       0
social_interaction_hours       0
relationship_status            0
gpa_or_performance_score       0
missed_deadlines               0
productivity_drop_percent      0
absenteeism_days               0
internet_speed_mbps            0
screen_time_total_hours        0
behavioral_cluster             0
addiction_score                0
addiction_binary               0
addiction_severity             0
burnout_probability            0
mental_health_risk_score       0
churn_probability              0
dtype: int64