# 31st May 2026

In [ ]:
import json 

data='''
{
"name": "Alice",
"age": 30,
"skills": ["Python", "Data Science", "Machine Learning"],
"address": {
    "street": "123 Main St",
    "city": "New York",
    "country": "USA" 
    }
}
'''

json.loads(data) # -- JSON to dictionary

{'name': 'Alice',
 'age': 30,
 'skills': ['Python', 'Data Science', 'Machine Learning'],
 'address': {'street': '123 Main St', 'city': 'New York', 'country': 'USA'}}

In [ ]:
data = {'name': 'Alice',
        'age': 30,
        'skills': ['Python', 'Data Science', 'Machine Learning'],
        'address': {'street': '123 Main St', 'city': 'New York', 'country': 'USA'}}

print(json.dumps(data, indent=2))  # -- Dictionary to JSON with indentation for better readability

{
  "name": "Alice",
  "age": 30,
  "skills": [
    "Python",
    "Data Science",
    "Machine Learning"
  ],
  "address": {
    "street": "123 Main St",
    "city": "New York",
    "country": "USA"
  }
}

In [ ]:
with open(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\mydata.json", "w") as f:
    json.dump(data, f, indent=2) # -- Writing JSON data to a file with indentation for better readability

In [ ]:
with open(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\mydata.json", "r") as f:
    result = json.load(f)  # -- Reading JSON data from a file and converting it back to a Python dictionary
print(result)

{'name': 'Alice', 'age': 30, 'skills': ['Python', 'Data Science', 'Machine Learning'], 'address': {'street': '123 Main St', 'city': 'New York', 'country': 'USA'}}

In [6]:
!pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.17-py3-none-any.whl.metadata (6.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl (158 kB)
Downloading idna-3.17-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ------------------------ --------------- 3/5 [certifi]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.17 requests-2.34.2 urllib3-2.7.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import requests

url="https://jsonplaceholder.typicode.com/users"
response=requests.get(url)
print(response.status_code) # -- Checking the status code of the response
#print(response.headers) # -- Printing the headers of the response   
#print(response.text) # -- Printing the raw JSON response as a string
data=response.json() # -- Parsing the JSON response into a Python dictionary 
print(data)# -- Printing the parsed JSON data as a Python dictionary
print(type(data)) # -- Checking the type of the parsed JSON data (should be a list of dictionaries)
print(type(data[0])) # -- dictionary

200
[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]
<class 'list'>
<class 'dict'>

In [ ]:
import json

url1 ="https://jsonplaceholder.typicode.com/posts"

data= {
    "id": 101,
    "userId": 1,
    "title": "python",
    "body": "learning APi"
}

response = requests.post(url1,json=data)
response.status_code # -- Checking the status code of the response to ensure the POST request was successful

201

In [21]:
import json

url1 ="https://jsonplaceholder.typicode.com/posts/1"

data= {
    "id": 1,
    "userId": 1,
    "title": "python",
    "body": "learning APi"
}

response = requests.put(url1,json=data)
response.status_code # -- Checking the status code of the response to ensure the POST request was successful
response.json() # -- Printing the response from the server after the PUT request to see the updated data

{'id': 1, 'userId': 1, 'title': 'python', 'body': 'learning APi'}

In [23]:
import json

url1 ="https://jsonplaceholder.typicode.com/posts/1"

data= {
    "id": 1,
    "userId": 1,
    "title": "python",
    "body": "learning APi"
}

response = requests.delete(url1)
response.status_code # -- Checking the status code of the response to ensure the DELETE request was successful
response.json() # -- Printing the response from the server after the DELETE request to see the result of the deletion

{}

In [24]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\aiml_new\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\aiml_new\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------------- -------------------------- 3.4/9.8 MB 24.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 26.5 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 23.2 MB/s  0:00:00
Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----------------- ---------------------- 5.2/12.3 MB 26.6 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 29.4 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 24.9 MB/s  0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# PANDAS

In [71]:
import pandas as pd

#single row data as Series or one dimensional array like list

data = pd.Series([10,20,30,40,50])
print(data) # -- Printing the Series object to see the values and their corresponding indices
print(type(data)) # -- Checking the type of the data variable to confirm it's a pandas Series <class 'pandas.Series'>  

data.index # -- Accessing the index of the Series to see the default integer indices assigned to each value


# to change index

data1 = pd.Series([10,20,30,40,50], index=['a', 'b', 'c', 'd', 'e']) # -- Creating a Series with custom indices
print(data1) # -- Printing the Series object to see the values and their corresponding custom indices
print(data1['c']) # -- Accessing the value at index 'c' to see the corresponding value (30 in this case)
print(data1.values) # -- Accessing the values of the Series to see the array of values without the indices

data1=data1+10 # -- Adding 10 to each value in the Series to see the result of the operation applied to all values
print(data1) # -- Printing the original Series again to confirm that the original data has not been modified by the previous operation
print(data1.mean()) # -- Calculating the mean (average) of the values in the Series to see the result of the aggregation function applied to the data
print(data1.sum()) # -- Calculating the sum of the values in the Series to see the result of the aggregation function applied to the data
print(data1.min()) # -- Finding the minimum value in the Series to see the result of the aggregation function applied to the data
print(data1.max()) # -- Finding the maximum value in the Series to see the result of the aggregation function applied to the data

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.Series'>
a    10
b    20
c    30
d    40
e    50
dtype: int64
30
[10 20 30 40 50]
a    20
b    30
c    40
d    50
e    60
dtype: int64
40.0
200
20
60

In [ ]:
import pandas as pd

data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    "Course": ['Python', 'Data Science', 'Machine Learning', 'AI', 'Deep Learning']
}

df=pd.DataFrame(data) # -- Creating a DataFrame from the provided dictionary data
df

      Name            Course
0    Alice            Python
1      Bob      Data Science
2  Charlie  Machine Learning
3    David                AI
4      Eve     Deep Learning

In [37]:
import pandas as pd
df1 = pd.DataFrame()

df1['Name'] = ['Aliceadasdasd', 'Basdasdob', 'Charlie', 'David', 'Eve']
df1['Course'] = ['Python', 'Data Scasdasdience', 'Machiadasdne Learning', 'AI', 'Deep Learning']
df1

            Name                 Course
0  Aliceadasdasd                 Python
1      Basdasdob     Data Scasdasdience
2        Charlie  Machiadasdne Learning
3          David                     AI
4            Eve          Deep Learning

In [ ]:
import pandas as pd

# data taken from https://www.kaggle.com/datasets/ajitashwath/gaming-addiction-dataset
df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\gaming_addiction.csv") # -- Reading a CSV file into a DataFrame
df

,user_id,age,gender,country,occupation,income_level,years_gaming,preferred_genre,platform,device_type,...,absenteeism_days,internet_speed_mbps,screen_time_total_hours,behavioral_cluster,addiction_score,addiction_binary,addiction_severity,burnout_probability,mental_health_risk_score,churn_probability
0,USR000001,21,Male,India,Employed,Middle,9,Sandbox,PC,Laptop,...,7,39.9,5.4,Casual Enjoyer,27.61,0,Mild,1.0,0.920,1.000
1,USR000002,25,Male,India,Employed,Lower-Middle,13,RPG,Mobile,Mixed,...,6,71.5,13.4,Streamer/Creator,55.51,1,Moderate,1.0,0.515,0.813
2,USR000003,26,Male,Brazil,Employed,Middle,14,RPG,PC+Mobile,High-end PC,...,7,119.4,12.3,Streamer/Creator,45.85,0,Moderate,1.0,0.720,0.947
3,USR000004,22,Male,South Korea,Employed,Upper-Middle,10,Strategy,PC+Mobile,Mobile,...,8,136.5,6.9,Toxic Competitor,39.87,0,Mild,1.0,0.520,0.660
4,USR000005,17,Female,India,Student,Middle,5,Strategy,PC,Laptop,...,6,78.8,9.3,Competitive Grinder,46.97,0,Moderate,1.0,0.585,0.867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,USR000246,23,Female,Japan,Streamer/Content Creator,Upper-Middle,11,MMORPG,PC+Console,Console,...,4,180.9,7.2,Streamer/Creator,42.37,0,Moderate,1.0,0.395,0.590
246,USR000247,18,Male,India,Student,Low,6,Sandbox,PC,Mid-range PC,...,0,91.5,5.6,Social Gamer,22.45,0,Mild,1.0,0.715,0.803
247,USR000248,20,Male,USA,Student,Middle,8,MMORPG,Mobile,Console,...,8,120.6,4.9,Escape Seeker,34.76,0,Mild,1.0,0.410,0.939
248,USR000249,19,Male,South Korea,Employed,Middle,7,Sandbox,PC+Console,High-end PC,...,2,175.9,5.2,Social Gamer,36.60,0,Mild,1.0,0.405,0.870
249,USR000250,27,Male,USA,Unemployed,Middle,14,MMORPG,PC+Mobile,Laptop,...,4,131.7,4.8,Social Gamer,41.65,0,Moderate,1.0,0.605,0.733

In [42]:
import pandas as pd

# data taken from https://www.kaggle.com/datasets/rbansalasr/excel-data-file?select=Historicalinvesttemp.xlsx
df= pd.read_excel(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Historicalinvesttemp.xlsx") # -- Reading an Excel file into a DataFrame
df

   Unnamed: 0                        Unnamed: 1 Unnamed: 2 Unnamed: 3
0         NaN                               NaN        NaN        NaN
1         NaN                               NaN        NaN        NaN
2         NaN                               NaN        NaN        NaN
3         NaN                               NaN        NaN        NaN
4         NaN  Annual Returns on Investments in        NaN        NaN
..        ...                               ...        ...        ...
85       2007                            0.0549     0.0988     0.0466
86       2008                             -0.37     0.2587      0.016
87       2009                            0.2646     -0.149      0.001
88        NaN                            stocks     tbills      bonds
89   averages                               NaN        NaN        NaN

[90 rows x 4 columns]

In [ ]:
!pip install openpyxl # ! means it's a shell command to install the openpyxl library, which is used for reading and writing Excel files in Python.

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
import pandas as pd
df= pd.read_json(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\mydata.json") # -- Reading a JSON file into a DataFrame
df

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [ ]:
import pandas as pd

# data taken from https://www.kaggle.com/datasets/ajitashwath/gaming-addiction-dataset
df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\gaming_addiction.csv") # -- Reading a CSV file into a DataFrame
df.head() # -- Displaying the first few rows of the DataFrame to get an overview of the data
df.tail(7) # -- Displaying the last 7 rows of the DataFrame to get a more detailed overview of the data
df.shape # -- Checking the shape of the DataFrame to see the number of rows and columns
df.columns # -- Displaying the column names of the DataFrame to understand the structure of the data
df.dtypes   # -- Checking the data types of each column in the DataFrame to understand the types of data being stored
df.info() # -- Getting a concise summary of the DataFrame, including the number of non-null entries and data types of each column
df.describe() # -- Generating descriptive statistics of the DataFrame to understand the distribution and central tendencies of the numerical data
df['age'].describe() # -- Generating descriptive statistics specifically for the 'age' column to understand its distribution and central tendencies
df['age'] # -- Displaying the 'age' column of the DataFrame to see the individual age values for each entry
df[['age','occupation']] # -- Displaying the 'age' and 'occupation' columns of the DataFrame to see the values for these specific columns

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 49 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      250 non-null    str
 1   age                          250 non-null    int64
 2   gender                       250 non-null    str
 3   country                      250 non-null    str
 4   occupation                   250 non-null    str
 5   income_level                 250 non-null    str
 6   years_gaming                 250 non-null    int64
 7   preferred_genre              250 non-null    str
 8   platform                     250 non-null    str
 9   device_type                  250 non-null    str
 10  rank_tier                    250 non-null    str
 11  daily_playtime_hours         250 non-null    float64
 12  weekly_play_sessions         250 non-null    int64
 13  late_night_sessions_hours    250 non-null    float64
 14  weekend_playtime_hours       250 non-null    float64
 15  consecutive_hours_max        250 non-null    float64
 16  multiplayer_ratio            250 non-null    float64
 17  toxic_chat_reports           250 non-null    int64
 18  rage_quit_frequency          250 non-null    int64
 19  in_game_purchases            250 non-null    int64
 20  monthly_spending_usd         250 non-null    float64
 21  lootbox_openings             250 non-null    int64
 22  subscription_status          168 non-null    str
 23  stress_score                 250 non-null    float64
 24  loneliness_score             250 non-null    float64
 25  dopamine_dependency_index    250 non-null    float64
 26  self_control_score           250 non-null    float64
 27  impulsiveness_score          250 non-null    float64
 28  anxiety_level                250 non-null    float64
 29  depression_indicator         239 non-null    float64
 30  emotional_stability          250 non-null    float64
 31  sleep_hours                  250 non-null    float64
 32  exercise_frequency_per_week  250 non-null    int64
 33  caffeine_intake_cups_day     250 non-null    int64
 34  social_interaction_hours     250 non-null    float64
 35  relationship_status          250 non-null    str
 36  gpa_or_performance_score     240 non-null    float64
 37  missed_deadlines             250 non-null    int64
 38  productivity_drop_percent    250 non-null    float64
 39  absenteeism_days             250 non-null    int64
 40  internet_speed_mbps          250 non-null    float64
 41  screen_time_total_hours      250 non-null    float64
 42  behavioral_cluster           250 non-null    str
 43  addiction_score              250 non-null    float64
 44  addiction_binary             250 non-null    int64
 45  addiction_severity           234 non-null    str
 46  burnout_probability          250 non-null    float64
 47  mental_health_risk_score     250 non-null    float64
 48  churn_probability            250 non-null    float64
dtypes: float64(24), int64(12), str(13)
memory usage: 95.8 KB

     age                occupation
0     21                  Employed
1     25                  Employed
2     26                  Employed
3     22                  Employed
4     17                   Student
..   ...                       ...
245   23  Streamer/Content Creator
246   18                   Student
247   20                   Student
248   19                  Employed
249   27                Unemployed

[250 rows x 2 columns]

In [58]:
df.loc[4] # -- Accessing the row at index 4 of the DataFrame to see the values for that specific entry
df.loc[0:5] # -- Accessing the rows from index 0 to 4 (inclusive) of the DataFrame to see the values for those entries

,user_id,age,gender,country,occupation,income_level,years_gaming,preferred_genre,platform,device_type,...,absenteeism_days,internet_speed_mbps,screen_time_total_hours,behavioral_cluster,addiction_score,addiction_binary,addiction_severity,burnout_probability,mental_health_risk_score,churn_probability
0,USR000001,21,Male,India,Employed,Middle,9,Sandbox,PC,Laptop,...,7,39.9,5.4,Casual Enjoyer,27.61,0,Mild,1.00,0.920,1.000
1,USR000002,25,Male,India,Employed,Lower-Middle,13,RPG,Mobile,Mixed,...,6,71.5,13.4,Streamer/Creator,55.51,1,Moderate,1.00,0.515,0.813
2,USR000003,26,Male,Brazil,Employed,Middle,14,RPG,PC+Mobile,High-end PC,...,7,119.4,12.3,Streamer/Creator,45.85,0,Moderate,1.00,0.720,0.947
3,USR000004,22,Male,South Korea,Employed,Upper-Middle,10,Strategy,PC+Mobile,Mobile,...,8,136.5,6.9,Toxic Competitor,39.87,0,Mild,1.00,0.520,0.660
4,USR000005,17,Female,India,Student,Middle,5,Strategy,PC,Laptop,...,6,78.8,9.3,Competitive Grinder,46.97,0,Moderate,1.00,0.585,0.867
5,USR000006,13,Male,USA,Freelancer,Middle,1,Horror,PC,Mobile,...,3,93.8,3.7,Casual Enjoyer,17.26,0,NaN,0.32,0.400,0.150

In [ ]:
df.iloc[0:5,0:3] # -- Accessing the first 5 rows and the first 3 columns of the DataFrame to see the values for those specific entries and columns

     user_id  age  gender
0  USR000001   21    Male
1  USR000002   25    Male
2  USR000003   26    Male
3  USR000004   22    Male
4  USR000005   17  Female