In [18]:
import pandas as pd


df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") # -- Reading a CSV file into a DataFrame
df

df.isna().sum()

#df['society'].isna().sum()

#df.shape -- (13320, 9)
#len(df) --13320

# % of null values
df = df[df.columns[df.isna().sum()*100/len(df)<30]] #- removed column where you have more than 30% null values

df.isna().sum()

df = df.dropna() # even if single column is null in that row. .. that row will be deleted.. so drop na will delete rows

df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [26]:
import pandas as pd


df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") # -- Reading a CSV file into a DataFrame
df = df[df.columns[df.isna().sum()*100/len(df)<30]] #- removed column where you have more than 30% null values

df.isna().sum()
#df.fillna(value="not given",inplace=True) # this will not work as not given is string nd u cannot given it to all columns as few are int / float

#df.isna().sum()

df.fillna({
    "area_types": "----Built-up  Area",
    "availability" : "----Ready To Move	"
}
)
df.isna().sum()
#df = df.dropna() # even if single column is null in that row. .. that row will be deleted.. so drop na will delete rows

#df

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [ ]:
import pandas as pd


df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") # -- Reading a CSV file into a DataFrame
df = df[df.columns[df.isna().sum()*100/len(df)<30]] #- removed column where you have more than 30% null values

df.isna().sum()


df.fillna({
    'area_type': df['area_type'].mode()[0],
    'availability': df['availability'].mode()[0],
    'bath': df['bath'].median(),
    'price': df['price'].mean(),

},inplace=True
)
# instead of using any constant value to replace we use mean mediun apprach


df.isna().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath              0
balcony         609
price             0
dtype: int64

In [ ]:
import pandas as pd


df= pd.read_csv(r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Data\Bengaluru_House_Data.csv") # -- Reading a CSV file into a DataFrame
df = df[df.columns[df.isna().sum()*100/len(df)<30]] #- removed column where you have more than 30% null values

# 13315	Built-up  Area	Ready To Move	Whitefield	5 Bedroom	3453	4.0	0.0	231.00
# 13316	Super built-up  Area	Ready To Move	Richards Town	4 BHK	3600	5.0	NaN	400.00
df.ffill(inplace=True) # forward fill means if 13316 row is having null value in any column it will pick the value from 
# row 13315 for the same column n fill in 13316

#13315	Built-up  Area	Ready To Move	Whitefield	5 Bedroom	3453	4.0	0.0	231.00
#13316	Super built-up  Area	Ready To Move	Richards Town	4 BHK	3600	5.0	0.0	400.00

# same way we have backward fill 

df.bfill(inplace=True)

#13315	Built-up  Area	Ready To Move	Whitefield	5 Bedroom	3453	4.0	0.0	231.00
#13316	Super built-up  Area	Ready To Move	Richards Town	4 BHK	3600	5.0	1.0	400.00
#13317	Built-up  Area	Ready To Move	Raja Rajeshwari Nagar	2 BHK	1141	2.0	1.0	60.00


# # -- it is advised to use both as if 1st row or last row column is null then it will rename null until we use 
# both -- 

'''

inplace=True Directly modifies the original df in memory 
inplace=False (Default)Behavior DirectlyReturns a new copy of the DataFrame with the filled values.

'''

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [ ]:
import pandas as pd

df=pd.DataFrame()

df['Emp_id']=[101,102,103,104,105,106,107,108]
df['Emp_name']=['rupahli1','rupahli2','rupahli3','rupahli4','rupahli5','rupahli6','rupahli7','rupahli8']
df


df2=pd.DataFrame()


df2['Emp_id'] = [102,105,108,110,112]
df2['Bank_Name'] = ['SBI','HDFC','SBI','SBI','HDFC']
df2['Balance'] = [10,20,30,40,50]
df2

df3 = pd.merge(left=df,right=df2,how='inner')  # inner means - common of both the df
df3

df4 = pd.merge(left=df,right=df2,how='outer') # outer means - OR condition .. union of both .. all will come
df4

df5 = pd.merge(left=df,right=df2,how='cross') # cross means -- multiple -- 101 mutiplied but all 5 rows.. so post merging total 8x% = 40 rows
df5

df6 = pd.merge(left=df,right=df2,how='left') # left means -- keep all from left and map them from right .. 
df6

df7 = pd.merge(left=df,right=df2,how='right') # left means -- keep all from right and map them from left .. 
df7

   Emp_id  Emp_name Bank_Name  Balance
0     102  rupahli2       SBI       10
1     105  rupahli5      HDFC       20
2     108  rupahli8       SBI       30
3     110       NaN       SBI       40
4     112       NaN      HDFC       50