# Beginner Module

In [8]:
!pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.50-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 16.1 MB/s  0:00:00
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.1-cp313-cp313-win_amd64.whl (238 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/4 [typing-extensions]
   ---------- ----------------------------- 1/4 [pymysql]
   ---------- ----------------------------- 1/4 [pymysql]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.5.1 pymysql-1.2.0 sqlalchemy-2.0.50 typing-extensions-4.15.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
## connect with database and add csv data to table n read from it

import pandas as pd
import mysql.connector
import json
from sqlalchemy import create_engine

df = pd.read_csv("Data/Pandas - Q1 Sales.csv")
df

 

with open (r"C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\AIML\Code\connection.json",mode="r+") as tf:
    config=  json.load(tf)

connection = mysql.connector.connect(
    host=config['host'],
    user=config['user'],
    password=config['password'],
    database=config['database']

)

connection_string = f"mysql+pymysql://{config['user']}:{config['password']}@{config['host']}:3306/{config['database']}"
engine = create_engine(connection_string)

connection 

df.to_sql(name="sales_information",con=engine, if_exists="append", index=False)

df_sql = pd.read_sql_table(table_name="sales_information",con=engine)

df_sql

<>:6: SyntaxWarning: invalid escape sequence '\P'
<>:6: SyntaxWarning: invalid escape sequence '\P'
C:\Users\KITTU-PALKIN\AppData\Local\Temp\ipykernel_22248\2600478063.py:6: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("Data\Pandas - Q1 Sales.csv")

      Country Region Sales Person    Date of Purchase   Total  Quantity
0       India  North         John    9/4/2017 0:00:00  100000       567
1          US  North         Bill    8/3/2014 0:00:00  120000      3000
2          UK  North       Thomas    8/1/2013 0:00:00  140000       345
3   Australia   East         John   7/31/2014 0:00:00  160000      1000
4      Africa   East         Bill    5/5/2012 0:00:00  180000       123
..        ...    ...          ...                 ...     ...       ...
75         US   West         John   10/1/2014 0:00:00  220000        90
76         UK   West         Bill  12/14/2011 0:00:00  240000        90
77  Australia   West       Thomas    7/1/2014 0:00:00  260000        90
78     Africa  North         John   9/27/2010 0:00:00  140000        85
79  Singapore  North         Bill   1/28/2013 0:00:00  150000        85

[80 rows x 6 columns]

In [ ]:
## add new data - column or row

import pandas as pd

df = pd.read_csv("Data/Pandas - Q1 Sales.csv")
df
calls_made = range(20)
df['calls_made'] = calls_made # adding column

df

new_row = ['India',	'North',	'John',	'9/4/2017 0:00:00',	'100000'	,'567',	'0']

new_row_df = pd.DataFrame([new_row],columns=df.columns.values) # convert list row to dataframe row - 
#adding columns above is necesarry otheriwse it will not be able to map 
df_result = pd.concat([df, new_row_df], ignore_index=True) # now add in dataframe

df_result

<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:5: SyntaxWarning: invalid escape sequence '\P'
C:\Users\KITTU-PALKIN\AppData\Local\Temp\ipykernel_22248\934039073.py:5: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("Data\Pandas - Q1 Sales.csv")

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,calls_made
0,India,North,John,9/4/2017 0:00:00,100000,567,0
1,US,North,Bill,8/3/2014 0:00:00,120000,3000,1
2,UK,North,Thomas,8/1/2013 0:00:00,140000,345,2
3,Australia,East,John,7/31/2014 0:00:00,160000,1000,3
4,Africa,East,Bill,5/5/2012 0:00:00,180000,123,4
5,Singapore,East,Thomas,8/7/2010 0:00:00,200000,1000,5
6,Mylasia,West,John,1/30/2014 0:00:00,1000000,7890,6
7,India,West,Bill,9/30/2012 0:00:00,240000,200,7
8,US,West,Thomas,5/3/2014 0:00:00,26000000,1000,8
9,UK,North,John,11/14/2017 0:00:00,100000,1000,9
10,Australia,North,Bill,1/28/2016 0:00:00,120000,567,10
11,Africa,North,Thomas,10/28/2010 0:00:00,140000,1000,11
12,Singapore,East,John,2/28/2017 0:00:00,160000,892,12
13,Mylasia,East,Bill,5/8/2017 0:00:00,180000,444,13
14,India,East,Thomas,8/20/2010 0:00:00,200000,90,14
15,US,West,John,10/1/2014 0:00:00,220000,90,15
16,UK,West,Bill,12/14/2011 0:00:00,240000,90,16
17,Australia,West,Thomas,7/1/2014 0:00:00,260000,90,17
18,Africa,North,John,9/27/2010 0:00:00,140000,85,18
19,Singapore,North,Bill,1/28/2013 0:00:00,150000,85,19
20,India,North,John,9/4/2017 0:00:00,100000,567,0

In [ ]:
import pandas as pd

df = pd.read_csv("Data/Pandas - Q1 Sales.csv")
#print(pd.read_csv.__doc__)  #----> how to check documentation


#new_row_df = pd.DataFrame([new_row],columns=df.columns.values) # convert list row to dataframe row 

print(pd.DataFrame.__doc__) #----> how to check documentation

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3

<>:3: SyntaxWarning: invalid escape sequence '\P'
<>:3: SyntaxWarning: invalid escape sequence '\P'
C:\Users\KITTU-PALKIN\AppData\Local\Temp\ipykernel_22248\2347189921.py:3: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("Data\Pandas - Q1 Sales.csv")

# Intermediate Module

In [ ]:
import random
po_number= [int(f"1000{i}") for i in range(20)]
po_number
random.shuffle(po_number)
po_number

import pandas as pd

df = pd.read_csv("Data/Pandas - Q1 Sales.csv")

df['po_number'] = po_number

df.set_index('po_number',inplace=True)

## permanently converts the po_number column into the row labels (index) of your existing DataFrame.
## By default, Pandas numbers your rows sequentially starting from 0.
## The sequence numbers are removed, and the po_number column becomes the new index. 
# By default, it is removed from the list of standard columns
#If you need to keep po_number as a regular column while also copying it into the index, pass drop=False:

df

df.sort_index() #by index
df.sort_index(ascending=False)

df.sort_values(['Country','Region']) # by column

# to change in dataframe - use inpace

df.sort_values(['Country','Region'] , inplace=True)
df

<>:9: SyntaxWarning: invalid escape sequence '\P'
<>:9: SyntaxWarning: invalid escape sequence '\P'
C:\Users\KITTU-PALKIN\AppData\Local\Temp\ipykernel_22248\2157051078.py:9: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("Data\Pandas - Q1 Sales.csv")

,Country,Region,Sales Person,Date of Purchase,Total,Quantity
po_number,,,,,,
100011,Africa,East,Bill,5/5/2012 0:00:00,180000,123
100014,Africa,North,Thomas,10/28/2010 0:00:00,140000,1000
10001,Africa,North,John,9/27/2010 0:00:00,140000,85
100010,Australia,East,John,7/31/2014 0:00:00,160000,1000
10007,Australia,North,Bill,1/28/2016 0:00:00,120000,567
100013,Australia,West,Thomas,7/1/2014 0:00:00,260000,90
10004,India,East,Thomas,8/20/2010 0:00:00,200000,90
100019,India,North,John,9/4/2017 0:00:00,100000,567
10008,India,West,Bill,9/30/2012 0:00:00,240000,200
100012,Mylasia,East,Bill,5/8/2017 0:00:00,180000,444
100016,Mylasia,West,John,1/30/2014 0:00:00,1000000,7890
100015,Singapore,East,Thomas,8/7/2010 0:00:00,200000,1000
10005,Singapore,East,John,2/28/2017 0:00:00,160000,892
10009,Singapore,North,Bill,1/28/2013 0:00:00,150000,85
100018,UK,North,Thomas,8/1/2013 0:00:00,140000,345
10000,UK,North,John,11/14/2017 0:00:00,100000,1000
100017,UK,West,Bill,12/14/2011 0:00:00,240000,90
10006,US,North,Bill,8/3/2014 0:00:00,120000,3000
10003,US,West,Thomas,5/3/2014 0:00:00,26000000,1000
10002,US,West,John,10/1/2014 0:00:00,220000,90

## Datetime

In [62]:
import pandas as pd

df = pd.read_csv("Data/Pandas - Q1 Sales.csv")

df

df['Date of Purchase'][0]

type(df['Date of Purchase'][0]) #str

pd.to_datetime(df['Date of Purchase'][0])  #Timestamp('2017-09-04 00:00:00') 

## convert column values to date time in df

df['Date of Purchase'] =  pd.to_datetime(df['Date of Purchase'])

df

## if you need to fetch year ,month , day ..lets add three new column-- USE DT

df['year'] = df['Date of Purchase'].dt.year
df['month'] = df['Date of Purchase'].dt.month
df['day'] = df['Date of Purchase'].dt.day

df

df['Quantity'].max()
df['Quantity'].min()

df[['Quantity','Total']].min()

df.min()  # sorts and apply on columns
df.max()
df['Quantity'].mean()

## to fetch row where total is hightest
##understand below syntax
df[['Sales Person','Quantity', 'Total']][df['Total'] == df['Total'].max()] 

## correlation Matrix

df[['Quantity', 'Total']].corr()

          Quantity    Total
Quantity   1.00000  0.03126
Total      0.03126  1.00000

# Advanced Module